PACKAGE_NAME="samsung-galaxybook-battery"
PACKAGE_VERSION="1.0.0"
BUILT_MODULE_NAME[0]="samsung_galaxybook_battery"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"
